# Generated by Django 3.0 on 2020-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prii',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(max_length=500),
        ),
    ]
