# Generated by Django 3.0 on 2020-06-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMP',
        ),
    ]
